//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwapClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.r_user_quest = new HashSet<r_user_quest>();
        }
    
        public string client_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string birthday_date { get; set; }
        public string email { get; set; }
        public string sex { get; set; }
        public System.DateTime last_login { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<r_user_quest> r_user_quest { get; set; }
    }
}
