//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwapClassLibrary.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SwapDbConnection : DbContext
    {
        public SwapDbConnection()
            : base("name=SwapDbConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<business> businesses { get; set; }
        public virtual DbSet<BusinessOwner> BusinessOwners { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<google_value> google_value { get; set; }
        public virtual DbSet<main_category> main_category { get; set; }
        public virtual DbSet<place> places { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<quest> quests { get; set; }
        public virtual DbSet<r_place_quest> r_place_quest { get; set; }
        public virtual DbSet<r_place_sub_and_main_category> r_place_sub_and_main_category { get; set; }
        public virtual DbSet<r_sub_and_main_category> r_sub_and_main_category { get; set; }
        public virtual DbSet<sub_category> sub_category { get; set; }
    }
}
