//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwapClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class place
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public place()
        {
            this.r_business_place = new HashSet<r_business_place>();
            this.r_place_quest = new HashSet<r_place_quest>();
            this.r_place_sub_and_main_category = new HashSet<r_place_sub_and_main_category>();
        }
    
        public string place_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public string description { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public string opening_houers { get; set; }
        public string Icon { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string address_id { get; set; }
    
        public virtual address address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<r_business_place> r_business_place { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<r_place_quest> r_place_quest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<r_place_sub_and_main_category> r_place_sub_and_main_category { get; set; }
    }
}
