//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwapClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_google_main_category
    {
        public string main_id { get; set; }
        public string google_value_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual google_value google_value { get; set; }
        public virtual main_category main_category { get; set; }
    }
}
