//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwapClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_place_sub_and_main_category
    {
        public string sub_id { get; set; }
        public string main_id { get; set; }
        public string place_id { get; set; }
        public System.DateTime creation_date { get; set; }
    
        public virtual place place { get; set; }
        public virtual r_sub_and_main_category r_sub_and_main_category { get; set; }
    }
}
