//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwapClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_place_quest
    {
        public string place_id { get; set; }
        public string quest_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public string name { get; set; }
        public Nullable<decimal> Rating { get; set; }
    
        public virtual place place { get; set; }
        public virtual quest quest { get; set; }
    }
}
