//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwapClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_sub_and_main_category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public r_sub_and_main_category()
        {
            this.r_place_sub_and_main_category = new HashSet<r_place_sub_and_main_category>();
        }
    
        public string sub_id { get; set; }
        public string main_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public string descrition { get; set; }
        public Nullable<decimal> clicked { get; set; }
    
        public virtual main_category main_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<r_place_sub_and_main_category> r_place_sub_and_main_category { get; set; }
        public virtual sub_category sub_category { get; set; }
    }
}
