//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public string admin_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<decimal> phone { get; set; }
        public bool id_genus { get; set; }
        public System.DateTime date_register { get; set; }
        public System.DateTime last_login { get; set; }
    
        public virtual genu genu { get; set; }
    }
}
