//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api
{
    using System;
    using System.Collections.Generic;
    
    public partial class business
    {
        public string business_id { get; set; }
        public string id_type { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public Nullable<System.TimeSpan> opening_time { get; set; }
        public Nullable<System.TimeSpan> closing_time { get; set; }
        public Nullable<decimal> location_lat { get; set; }
        public Nullable<decimal> location_lng { get; set; }
        public Nullable<decimal> rating { get; set; }
    }
}
