//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SwapDbConnection : DbContext
    {
        public SwapDbConnection()
            : base("name=SwapDbConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<business> businesses { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<genu> genus { get; set; }
        public virtual DbSet<google_place_value> google_place_value { get; set; }
        public virtual DbSet<relationship_type_subType> relationship_type_subType { get; set; }
        public virtual DbSet<sube_type_categoriy> sube_type_categoriy { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<type_category> type_category { get; set; }
    }
}
