//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api
{
    using System;
    using System.Collections.Generic;
    
    public partial class relationship_type_subType
    {
        public string sub_type_id { get; set; }
        public string id_type { get; set; }
        public Nullable<decimal> clicked { get; set; }
    
        public virtual sube_type_categoriy sube_type_categoriy { get; set; }
        public virtual type_category type_category { get; set; }
    }
}
