//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api
{
    using System;
    using System.Collections.Generic;
    
    public partial class sube_type_categoriy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sube_type_categoriy()
        {
            this.relationship_type_subType = new HashSet<relationship_type_subType>();
        }
    
        public string sub_type_id { get; set; }
        public string client_value { get; set; }
        public string google_value_id { get; set; }
    
        public virtual google_place_value google_place_value { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<relationship_type_subType> relationship_type_subType { get; set; }
    }
}
